2310Hub: util.h util.c agent.h agent.c 2310A.c 2310hub.c
	gcc 2310A.c agent.c util.c  -pedantic -Wall -std=gnu99 -o 2310A
	gcc 2310B.c agent.c util.c -pedantic -Wall -std=gnu99 -o 2310B
	gcc 2310hub.c util.c -pedantic -Wall -std=gnu99 -o 2310hub
